defaults: &defaults
  adapter: mysql
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: listlibrary_development
test:
  <<: *defaults
  database: listlibrary_test

production:
  <<: *defaults
  database: listlibrary_production
  username: listlibrary
  password: 
